### PR TITLE
Add document to RAV storage adapter, adapter mod, tap_manager mod

### PR DESCRIPTION
**Pull request by ColePBryan**

### CODE REVIEW

**Comment by ColePBryan** [comment]
NOTE: if reviewers want to see the generated docs, clone repo and run `cargo doc --open`

**Review by aasseman — DISMISSED** [review]
LGTM

**Comment by ColePBryan** [comment]
@aasseman I just rebased with main and fixed an issue with the doc example code.

**Comment by ColePBryan** [comment]
@aasseman btw it seems like the CI will pass cargo test without running doc tests. We might want to fix that to help ensure any example code stays up to date.

**Comment by aasseman** [comment]
> @aasseman btw it seems like the CI will pass cargo test without running doc tests. We might want to fix that to help ensure any example code stays up to date.

https://github.com/taiki-e/cargo-llvm-cov/issues/2 :disappointed: 

I'll add a workaround in the CI for this. The doc's code passes now, so no need to wait for that.

**Review by aasseman — APPROVED** [review]
:shipit:

**Pull request merged**
